
services:
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  mongodb-atlas:
    image: mongodb/mongodb-atlas-local:8.0
    hostname: local_dev_atlas
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=mongodb
      - MONGODB_INITDB_ROOT_PASSWORD=mongodb
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

volumes:
  pgdata:
  mongo_data:
  mongo_config: